### ISSUE TITLE
Ajout des infos secretes

### ISSUE THREAD

**Issue by al31h** [al31h/hasstests#9]

**Comment by al31h** [comment]
Définition des infos dans secrets.yaml

Mise à jour de configuration.yaml. Attention à ne pas mettre de quotes pour les informations numériques (latitude, longitude, port knx)

```
homeassistant:
  name: '!secret home_name'
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  unit_system: metric
  time_zone: Europe/Paris

../..
  
knx:
  tunneling:
    host: '!secret knx_gateway_address'
    port: !secret knx_gateway_port
    local_ip: '!secret my_ip_address'

```

**Comment by al31h** [comment]
Après redémarrage :
- KNX : la connexion vers le gateway ne fonctionne pas : Could not connect to KNX interface: Gateway IP address is not a valid IPv4 address

La config correcte : ne pas mettre les adresses IP entre quotes
```
knx:
  tunneling:
    host: '!secret knx_gateway_address'
    port: !secret knx_gateway_port
    local_ip: '!secret my_ip_address'

```
